[workspace]
resolver = "2"
members = ["apps/server", "apps/theme-designer", "packages/shared-types"]
metadata.crane.name = "boluo"

[profile.release]
panic = "abort"

[profile.dev.package.sqlx-macros]
opt-level = 3

[patch.crates-io]
specta-macros = { git = "https://github.com/specta-rs/specta.git" }
specta = { git = "https://github.com/specta-rs/specta.git" }
specta-serde = { git = "https://github.com/specta-rs/specta.git" }
specta-typescript = { git = "https://github.com/specta-rs/specta.git" }
