services:
  db:
    image: docker.io/library/postgres:18-trixie
    build:
      context: ./apps/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boluo
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql
  redis:
    image: docker.io/library/redis
    volumes:
      - redis_data:/data

  storage:
    image: quay.io/minio/minio
    restart: unless-stopped
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9090"

  # Configure the object storage
  storage-init:
    image: quay.io/minio/mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
        sleep 2;
        until (/usr/bin/mc alias set dev http://storage:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}); do sleep 1; done;
        /usr/bin/mc mb dev/boluo;
        /usr/bin/mc anonymous set public dev/boluo;
        exit 0;
      "
volumes:
  postgres_data:
  redis_data:
  minio_data:
