# fly.toml app configuration file generated for boluo-server on 2025-05-11T06:42:07+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'boluo-server'
primary_region = 'nrt'
swap_size_mb = 512

[build]
  image = 'ghcr.io/mythal/boluo/server:production'

[deploy]
  strategy = 'bluegreen'

[env]
  HOST = '::'
  MAILGUN_DOMAIN = 'noreply.boluo.chat'
  PORT = '3000'
  PUBLIC_MEDIA_URL = 'https://media.boluo.chat'
  S3_BUCKET_NAME = 'boluo'
  S3_ENDPOINT_URL = 'https://9a7f9f4ce45406e8224c0f1e9e6785b5.r2.cloudflarestorage.com'
  RUST_LOG = 'info'

[http_service]
  internal_port = 3000
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '20s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/info/healthcheck'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 2
