[package]
name = "manage-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
dotenv = "0.15.0"
postgres = "0.19"

[dependencies.clap]
version = "4.1"
features = ["derive"]
