name: Postgres Image

on:
  schedule:
    - cron: "0 2 1 * *"
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - "apps/db/**"
      - ".github/workflows/boluo-postgres.yml"

permissions:
  contents: read
  packages: write

concurrency:
  group: boluo-postgres-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Push Multi-Arch Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout production
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/mythal/boluo/boluo-postgres
          tags: |
            type=raw,value=latest
            type=schedule,pattern=monthly-{{date 'YYYYMM'}}
            type=sha
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.description=The Boluo project customized Postgres image
            org.opencontainers.image.title=boluo-postgres

      - name: Build & Push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./apps/db
          file: ./apps/db/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo "Digest=${{ steps.build.outputs.digest }}"
